### ISSUE TITLE
Configure CO2 levels and buzzer sound via web interface

### ISSUE THREAD

**Issue by maehw** [maehw/coro2sens#1]
Wishes:
- Configure warn and critical CO2 level via web interface (instead of using compile-time definitions `CO2_WARN_PPM` and `CO2_CRITICAL_PPM` from `config.h`)
- Allow to switch buzzer sound on/off via web interface (nice to have: beep duration, tone pitch, etc.)

Idea:
- Store configuration values in non-volatile memory (EEPROM or internal flash)
- Read configuration values from non-volatile memory during start-up
- Allow reconfiguration of those values via web interface (store in non-volatile memory and also use those values without a re-start)

**Comment by mwb-experiments** [comment]
Fixed by latest commits.

**Comment by maehw** [comment]
Fixed by latest commits.
